CREATE TABLE public.equipamento (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,	
	nome varchar NOT NULL,
	tipo varchar NOT NULL,
	CONSTRAINT equipamento_pk PRIMARY KEY (id)
);

CREATE TABLE public.plano_treino (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar NOT NULL,
	descricao varchar NULL,
	inicio date NOT NULL,
	descanso int8 NOT NULL,
	ativo bool NOT NULL,
	CONSTRAINT plano_treino_pk PRIMARY KEY (id)
);

CREATE TABLE public.treino (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	quando date NOT NULL,
	id_plano_treino bigint NOT NULL,
	CONSTRAINT treino_pk PRIMARY KEY (id),
	CONSTRAINT treino_plano_treino_fk FOREIGN KEY (id_plano_treino) REFERENCES public.plano_treino(id)
);

CREATE TABLE public.exercicio (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar NOT NULL,
	quantidade_minima_repeticoes int8 NOT NULL,
	quantidade_maxima_repeticoes int8 NOT NULL,
	id_equipamento bigint NOT NULL,
	CONSTRAINT exercicio_pk PRIMARY KEY (id),
	CONSTRAINT exercicio_equipamento_fk FOREIGN KEY (id_equipamento) REFERENCES public.equipamento(id),
);

CREATE TABLE public.exercicio_plano_treino (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_exercicio int8 NOT NULL,
	id_plano_treino int8 NOT NULL,
	CONSTRAINT exercicio_plano_treino_pk PRIMARY KEY (id),
	CONSTRAINT exercicio_plano_treino_exercicio_fk FOREIGN KEY (id_exercicio) REFERENCES public.exercicio(id),
	CONSTRAINT exercicio_plano_treino_plano_treino_fk FOREIGN KEY (id_plano_treino) REFERENCES public.plano_treino(id)
);

CREATE TABLE public.exercicio_treino (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	quantidade_repeticoes int8 NOT NULL,
	minimo int8 NOT NULL,
	maximo int8 NOT NULL,
	id_treino bigint NOT NULL,
	CONSTRAINT exercicio_treino_pk PRIMARY KEY (id),
	CONSTRAINT exercicio_treino_treino_fk FOREIGN KEY (id_treino) REFERENCES public.treino(id)
);

